CREATE TABLE public.historique_prelevement
(
  id_prelevement integer,
  date character varying(21),
  nb_taxon_present smallint,
  collection_museum character varying(250),
  type_specimen character varying(250),
  code_specimen character varying(255),
  altitude_min bigint,
  mode_de_collecte character varying(250),
  toponyme character varying(250),
  toponymie_x double precision,
  toponymie_y double precision,
  information_complementaire text,
  id_loc integer,
  id_taxref integer NOT NULL,
  type_enregistrement integer,
  gps boolean,
  altitude_max integer,
  id_habitat integer,
  id_plante_hote integer,
  last_update timestamp without time zone,
  type_modification character varying(250),
  champ_modifie character varying(250),
  last_user_update character varying(250),
  source character varying(50)
);

CREATE TABLE public.historique_taxon
(
  id integer,
  cd_nom integer,
  cd_ref integer,
  cd_sup integer,
  lb_nom character varying(250) NOT NULL,
  lb_auteur character varying(250),
  nom_complet character varying(250),
  grande_terre boolean,
  iles_loyautee boolean,
  autre boolean,
  territoire_fr boolean,
  remarque text,
  sources text,
  id_espece integer,
  reference_description text,
  habitat smallint,
  id_ref integer,
  id_sup integer,
  nc character varying(4),
  rang character varying(4),
  last_update timestamp without time zone,
  type_modification character varying(250),
  champ_modifie character varying(250),
  last_user_update character varying(250),
  source character varying(50)
);