version: '3'
services:
    webapp:
        container_name: fatercal-web
        image: lschaeffer/fatercal-web:2.2-4
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /tmp/:/var/log/letsencrypt
        ports:
            - "80:80"
            - "443:443"
        links:
            - "postgres"
        environment:
            - DJANGO_DEBUG=false
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=fatercal
        env_file: fatercal-web.env
        # please define the variables DJANGO_SECRET_KEY (think to double any '$' character) and POSTGRES_PASSWORD in
        # fatercal-web.env file.
        # example of the environment file content :
        # DJANGO_SECRET_KEY=_4k52&$$59@7mas*mgmj7cipas*2+dz5h3nahw@po!3&q8^vhex
        # POSTGRES_PASSWORD=ftc

    postgres:
        container_name: fatercal-db
        image: postgres:9.6.6
        volumes:
            - /data/fatercal/postgresql:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=fatercal
            - POSTGRES_USER=fatercal
        env_file: fatercal-db.env

    cron:
        container_name: fatercal-cron
        image: lschaeffer/fatercal-cron:1.0
        ports:
            - "29:25"
        links:
            - "postgres"
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=fatercal
        env_file: fatercal-web.env

    api:
        container_name: fatercal-api
        image: lschaeffer/fatercal-api:1.0
        ports:
            - "5000:5000"
        links:
            - "postgres"
        environment:
            - DEBUG=false
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=fatercal
            - POSTGRES_USER=fatercal
        env_file:
            - fatercal-db.env
            - fatercal-api.env