version: '3'
services:
    webapp:
        container_name: fatercal-web
        image: acheype/fatercal-web:2.3.3
        build: ./fatercal_apps
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /tmp/:/var/log/letsencrypt
        ports:
            - "80:80"
            - "443:443"
        links:
            - "postgres"
        environment:
            - DJANGO_DEBUG=False
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=fatercal
        env_file: fatercal-web.env
        # please define the variables DJANGO_SECRET_KEY (think to double any '$' character) and POSTGRES_PASSWORD in
        # fatercal-web.env file.
        # example of the environment file content :
        # DJANGO_SECRET_KEY=_4k52&$$59@7mas*mgmj7cipas*2+dz5h3nahw@po!3&q8^vhex
        # POSTGRES_PASSWORD=ftc

    postgres:
        container_name: fatercal-db
        image: postgres:9.6.6
        volumes:
            - /data/fatercal/postgresql:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=fatercal
            - POSTGRES_USER=fatercal
        env_file: fatercal-db.env

#    pgadmin:
#        image: dpage/pgadmin4:4.4.30
#        volumes:
#            - /data/fatercal/pdadmin:/var/lib/pgadmin
#        ports:
#            - "8080:80"
#        links:
#            - "db:pgsql-server"
#        environment:
#            - PGADMIN_DEFAULT_EMAIL: herve.jourdan@ird.fr
#            - PGADMIN_DEFAULT_PASSWORD: fatercal
#            - PGADMIN_LISTEN_PORT: 8080

    cron:
        container_name: fatercal-cron
        image: lschaeffer/fatercal-cron:1.0
        ports:
            - "29:25"
        links:
            - "postgres"
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=fatercal
        env_file: fatercal-web.env

    api:
        container_name: fatercal-api
        image: lschaeffer/fatercal-api:1.0
        ports:
            - "81:81"
        links:
            - "postgres"
        environment:
            - DEBUG=False
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=fatercal
            - POSTGRES_USER=fatercal
        env_file:
            - fatercal-db.env
            - fatercal-api.env
