# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('d_docs', models.AutoField(primary_key=True, serialize=False)),
                ('citation', models.CharField(max_length=250)),
                ('reference', models.CharField(max_length=250)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'docs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocsUses',
            fields=[
                ('cd_docuse', models.AutoField(primary_key=True, serialize=False)),
                ('lb_docuse', models.TextField()),
            ],
            options={
                'db_table': 'docs_uses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HabitatDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'habitat_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hote',
            fields=[
                ('id_couple', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iso6393',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('part2b', models.CharField(blank=True, max_length=3, null=True)),
                ('part2t', models.CharField(blank=True, max_length=3, null=True)),
                ('part1', models.CharField(blank=True, max_length=2, null=True)),
                ('scope', models.CharField(max_length=1)),
                ('type', models.CharField(max_length=1)),
                ('ref_name', models.CharField(max_length=150)),
                ('comment', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'ISO_639-3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalite_localite', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('donnee_gps', models.BooleanField()),
            ],
            options={
                'db_table': 'localitee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toponyme', models.TextField()),
                ('prelevement', models.BooleanField()),
                ('museum', models.TextField(blank=True, null=True)),
                ('type_holotype_paratype', models.TextField(blank=True, db_column='type_holotype-paratype', null=True)),
                ('code_specimen', models.BigIntegerField(blank=True, null=True)),
                ('mode_de_collecte', models.TextField(blank=True, null=True)),
                ('complements', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'observation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanteHote',
            fields=[
                ('id_plante_hote', models.AutoField(db_column='id_plante-hote', primary_key=True, serialize=False)),
                ('famille', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('espece', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'plante_hote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taxref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_nom', models.IntegerField(blank=True, null=True, unique=True)),
                ('cd_ref', models.IntegerField(blank=True, null=True)),
                ('cd_sup', models.IntegerField(blank=True, null=True)),
                ('lb_nom', models.CharField(max_length=250, verbose_name='Nom')),
                ('lb_auteur', models.CharField(blank=True, max_length=250, null=True, verbose_name='Auteur')),
                ('nom_complet', models.CharField(blank=True, max_length=250, null=True)),
                ('grande_terre', models.NullBooleanField()),
                ('iles_loyautee', models.NullBooleanField()),
                ('autre', models.NullBooleanField()),
                ('territoire_fr', models.NullBooleanField()),
                ('remarque', models.TextField(blank=True, null=True)),
                ('sources', models.TextField(blank=True, null=True)),
                ('id_espece', models.IntegerField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'taxref',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxrefHabitat',
            fields=[
                ('habitat', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('lb_habitat', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'taxref_habitat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxrefRang',
            fields=[
                ('rang', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('lb_rang', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'taxref_rang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxrefStatus',
            fields=[
                ('status', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('lb_status', models.TextField()),
            ],
            options={
                'db_table': 'taxref_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taxvern',
            fields=[
                ('nom_vern', models.CharField(max_length=100)),
                ('id_taxvern', models.AutoField(primary_key=True, serialize=False)),
                ('cd_vern', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'taxvern',
                'managed': False,
            },
        ),
    ]
