version: '3'
services:
    www:
        container_name: fatercal-web
        build: ../..
        image: acheype/fatercal-www:0.8
        ports:
            - "80:80"
        links:
            - "postgres"
        environment:
            - DJANGO_DEBUG=false
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=fatercal
        env_file: ./fatercal-web.env
        # please define the variables DJANGO_SECRET_KEY (think to double any '$' character) and POSTGRES_PASSWORD in
        # fatercal-web.env file.
        # example of the environment file content :
        # DJANGO_SECRET_KEY=_4k52&$$59@7mas*mgmj7cipas*2+dz5h3nahw@po!3&q8^vhex
        # POSTGRES_PASSWORD=ftc

    postgres:
        container_name: fatercal-db
        image: postgres:9.6.6
        volumes:
            - /data/postgresql2:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=fatercal
            - POSTGRES_USER=fatercal
            - POSTGRES_PASSWORD=ftc
        env-file: ./fatercal-db.env
        # please define the variables POSTGRES_PASSWORD in fatercal-web.env file.
        # example of the environment file content :
        # POSTGRES_PASSWORD=ftc