# Generated by Django 2.2.20 on 2021-05-07 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fatercal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxon',
            old_name='taxrefversion',
            new_name='taxref_version',
        ),
        migrations.RenameField(
            model_name='taxrefupdate',
            old_name='taxrefversion',
            new_name='taxref_version',
        ),
        migrations.AlterField(
            model_name='vernaculaire',
            name='id_taxref',
            field=models.ForeignKey(db_column='id_taxref', on_delete=django.db.models.deletion.DO_NOTHING, related_name='noms_vern', to='fatercal.Taxon', verbose_name='Taxon'),
        ),
        migrations.RenameField(
            model_name='taxon',
            old_name='iles_loyautee',
            new_name='iles_loyaute',
        ),
        migrations.RenameField(
            model_name='taxon',
            old_name='id_espece',
            new_name='id_ancienne_bd',
        ),
    ]
