# Generated by Django 2.2.24 on 2021-10-10 00:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fatercal', '0002_model_update_for_api'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docsuses',
            old_name='id_docuse',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='docsuses',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RenameField(
            model_name='localisation',
            old_name='id_loc',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='localisation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RenameField(
            model_name='plantehote',
            old_name='id_plante_hote',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='plantehote',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RenameField(
            model_name='prelevement',
            old_name='id_prelevement',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='prelevement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RenameField(
            model_name='prelevement',
            old_name='information_complementaire',
            new_name='infos_compl',
        ),
        migrations.AlterField(
            model_name='prelevement',
            name='infos_compl',
            field=models.TextField(blank=True, null=True, verbose_name='Informations complémentaires'),
        ),
        migrations.RenameField(
            model_name='prelevement',
            old_name='nb_taxon_present',
            new_name='nb_individus',
        ),
        migrations.AlterField(
            model_name='prelevement',
            name='nb_individus',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Nombre Individus'),
        ),
        migrations.RenameField(
            model_name='typeloc',
            old_name='id_type',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='typeloc',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RenameField(
            model_name='vernaculaire',
            old_name='id_taxvern',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='vernaculaire',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RenameField(
            model_name='prelevement',
            old_name='id_loc',
            new_name='localisation',
        ),
        migrations.AlterField(
            model_name='prelevement',
            name='localisation',
            field=models.ForeignKey(blank=True, db_column='localisation', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='fatercal.Localisation',
                                    verbose_name='Localisation'),
        ),
        migrations.RenameField(
            model_name='recolteur',
            old_name='id_prelevement',
            new_name='prelevement',
        ),
        migrations.AlterField(
            model_name='recolteur',
            name='prelevement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='fatercal.Prelevement'),
        ),
        migrations.AlterField(
            model_name='prelevement',
            name='date',
            field=models.CharField(blank=True, max_length=23, null=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message="La date doit être dans l'une des formes suivantes : 1850, 1850-12, 1850-12-01", regex='(^\\d{4}$)|(^\\d{4}-(0[1-9]|1[0-2])$)|(^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|1\\d|2\\d|3[0-1])$)|(^$)|(^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|1\\d|2\\d|3[0-1])\\/\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|1\\d|2\\d|3[0-1])$)')]),
        ),
        migrations.AlterField(
            model_name='prelevement',
            name='habitat',
            field=models.ForeignKey(blank=True, db_column='id_habitat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fatercal.HabitatDetail'),
        ),
        migrations.AlterField(
            model_name='prelevement',
            name='plante_hote',
            field=models.ForeignKey(blank=True, db_column='id_plante_hote', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fatercal.PlanteHote'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='rang',
            field=models.ForeignKey(db_column='rang', on_delete=django.db.models.deletion.DO_NOTHING, to='fatercal.TaxrefRang'),
        ),
        migrations.AlterField(
            model_name='taxrefupdate',
            name='taxref_version',
            field=models.CharField(max_length=250),
        ),
    ]
