# Generated by Django 2.2.20 on 2021-05-27 20:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fatercal', '0002_model_update_for_api'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prelevement',
            old_name='information_complementaire',
            new_name='infos_compl',
        ),
        migrations.RenameField(
            model_name='prelevement',
            old_name='nb_taxon_present',
            new_name='nb_individus',
        ),
    ]
